### PR TITLE
Updates link to Ann Arbor's data

### PR DESCRIPTION
**Pull request by JohnMaguire**
Policy: http://www.a2gov.org/Pages/Policies-and-Notices.aspx

Hopefully I did this right? Wasn't sure where I could link the policy, if anywhere.

### CODE REVIEW

**Comment by SLarrick** [comment]
Hi @JohnMaguire, that link is to the "Policies and Notices" page for the Ann Arbor Data Catalogue, but it is not what we at Sunlight would consider a formally adopted "open data policy". It is essentially the "Terms and Conditions"/Disclaimer for using the data made available online and does not require or aspire to the establishment of an open data website, or, more fundamentally, require that Ann Arbor's government data be proactively released online (by default). The FAQ (http://www.a2gov.org/services/data/Pages/FAQs.aspx) is actually imo closer to what we are looking for, but neither are a part of the legal framework of the city (neither adopted by the city council or signed by the mayor/manager). Check out our open data policy guidelines (http://sunlightfoundation.com/opendataguidelines/), or examples of policies from other cities (linked in and below the map) for a better idea of what we are documenting.

If you or anyone from Ann Arbor is interested in furthering open data policy, do feel free to reach out and we are happy to support. If you think city hall might be interested in more formal open data technical assistance, I would encourage you to suggest they consider applying to the What Works Cities program: http://whatworkscities.bloomberg.org/

**Comment by jalbertbowden** [comment]
wondering if this can be closed...didn't read content, not trying to be rude at all, just running maintenance on a number of repositories currently, and it is much easier to have users tell me yay/nay vs. figuring it out myself.

**Comment by JohnMaguire** [comment]
Yes sorry, feel free to close it or I will myself when I get a chance. I
missed the original response. Thanks!

**Comment by jalbertbowden** [comment]
Closing now, thanks for the response!

**Pull request closed without merging**
